### ISSUE TITLE
UseCase：RollTheDieUsecase (擲骰子)

### ISSUE THREAD

**Issue by innocentliny** [Game-as-a-Service/cash-flow-game#50]

**Comment by SnackJump** [comment]
1. usecase 內用到的 repository 應該不用傳進去
![image](https://user-images.githubusercontent.com/28628745/220931672-6e8db351-a3d5-4524-9997-76b2cbbbe1b1.png)
    - 參考 https://github.com/Game-as-a-Service/Saboteur/blob/main/app/src/main/java/tw/waterballsa/gaas/saboteur/app/usecases/PlayCardUsecase.java
![image](https://user-images.githubusercontent.com/28628745/220932439-fb368c92-fa35-4ea1-bc46-b0c1bf5dfe55.png)

**Comment by SnackJump** [comment]
# chatGPT 回答
要測試RollDiceUseCase的話，你需要先建立一個Mockito的Mock物件來模擬Repository的行為，然後將這個Mock物件注入到RollDiceUseCase裡面。

下面是一個簡單的範例，展示如何使用@ExtendWith(MockitoExtension.class)來寫測試個案：


```java
@ExtendWith(MockitoExtension.class)
public class RollDiceUseCaseTest {

    @Mock
    private DiceRollRepository diceRollRepository;

    @InjectMocks
    private RollDiceUseCase rollDiceUseCase;

    @Test
    public void testRollDiceUseCase() {
        // 假設你已經有了一個RollDiceRequest物件
        RollDiceRequest request = new RollDiceRequest();

        // 當DiceRollRepository呼叫rollDice()方法時，回傳一個假的DiceRoll物件
        when(diceRollRepository.rollDice(anyInt())).thenReturn(new DiceRoll(6));

        // 呼叫RollDiceUseCase的rollDice()方法，並驗證回傳的結果是否符合預期
        RollDiceResponse response = rollDiceUseCase.rollDice(request);
        assertEquals(6, response.getDiceRoll().getValue());
    }
}
```
上面的程式碼中，我們使用@Mock注解建立一個DiceRollRepository的Mock物件，並使用@InjectMocks注解將RollDiceUseCase注入到測試中。在測試方法testRollDiceUseCase()中，我們使用Mockito的when()方法設定當diceRollRepository.rollDice()方法被呼叫時，回傳一個假的DiceRoll物件。然後我們呼叫RollDiceUseCase的rollDice()方法，並驗證回傳的結果是否符合預期。

**Comment by innocentliny** [comment]
> # chatGPT 回答
> 要測試RollDiceUseCase的話，你需要先建立一個Mockito的Mock物件來模擬Repository的行為，然後將這個Mock物件注入到RollDiceUseCase裡面。
> 
> 下面是一個簡單的範例，展示如何使用@ExtendWith(MockitoExtension.class)來寫測試個案：
> 
> ```java
> @ExtendWith(MockitoExtension.class)
> public class RollDiceUseCaseTest {
> 
>     @Mock
>     private DiceRollRepository diceRollRepository;
> 
>     @InjectMocks
>     private RollDiceUseCase rollDiceUseCase;
> 
>     @Test
>     public void testRollDiceUseCase() {
>         // 假設你已經有了一個RollDiceRequest物件
>         RollDiceRequest request = new RollDiceRequest();
> 
>         // 當DiceRollRepository呼叫rollDice()方法時，回傳一個假的DiceRoll物件
>         when(diceRollRepository.rollDice(anyInt())).thenReturn(new DiceRoll(6));
> 
>         // 呼叫RollDiceUseCase的rollDice()方法，並驗證回傳的結果是否符合預期
>         RollDiceResponse response = rollDiceUseCase.rollDice(request);
>         assertEquals(6, response.getDiceRoll().getValue());
>     }
> }
> ```
> 
> 上面的程式碼中，我們使用@mock注解建立一個DiceRollRepository的Mock物件，並使用@Injectmocks注解將RollDiceUseCase注入到測試中。在測試方法testRollDiceUseCase()中，我們使用Mockito的when()方法設定當diceRollRepository.rollDice()方法被呼叫時，回傳一個假的DiceRoll物件。然後我們呼叫RollDiceUseCase的rollDice()方法，並驗證回傳的結果是否符合預期。

嗯? ChatGPT 會講這些喔?

**Comment by innocentliny** [comment]
@SnackJump 

> 2.失業的測試個案要增加回合數的判斷
因 use case 沒有對玩家回合數異動，應是結束我的回合 use case 做的事情，所以就沒判斷了。

**Comment by innocentliny** [comment]
@SnackJump 

我修改了，

- use case 的 repository 改以建構式方式傳入。
- use case 增加回傳 event 物件。
